CREATE DATABASE IF NOT EXISTS meu_painel;
USE meu_painel;

CREATE TABLE IF NOT EXISTS topicos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_inicio DATE NULL,
    data_limite DATE NULL
);

CREATE TABLE IF NOT EXISTS itens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topico_id INT NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    concluido TINYINT(1) NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (topico_id) REFERENCES topicos(id) ON DELETE CASCADE
);
